language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
deploy:
  local_dir: doc
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: ${gh_token}
  keep_history: true
  on:
    branch: master